### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by owneril** [EliotVU/UT2004-MutBestTimes#2]
Hello @EliotVU ,
Nice work here.

Having some issues to get it to work correctly
For the compilation of the mutator,
Shouldn't there be the .u files?

Or if there is any .readme for the installation somewhere?

Thanks you very much
Regards,

**Comment by EliotVU** [comment]
Hey, thanks :)

I have added a readme to get you started, and I have also whitelisted any ip requests coming from BTimes, so you won't have to remove the protection at all :)

**Comment by owneril** [comment]
Amazing!
Hope the UT4 BT will be also great!
Here since the beginning of Elite trials!

**Comment by EliotVU** [comment]
Cool, what was your name on Elite Trials?
